apiVersion: v1
kind: Service
metadata:
  namespace: {{ .ClusterNamespace }}
  name: kube-controller-manager-prometheus-discovery
  labels:
    app: vcluster-controller
    release: {{ .ClusterName }}
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10257
    targetPort: 10257
  selector:
    app: vcluster-controller
    release: {{ .ClusterName }}
