apiVersion: v1
kind: Service
metadata:
  namespace: vcluster-vcluster1
  name: kube-controller-manager-prometheus-discovery
  labels:
    app: vcluster-controller
    release: vcluster1
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10257
    targetPort: 10257
  selector:
    app: vcluster-controller
    release: vcluster1
